### ISSUE TITLE
Can not install "Indicators.jl" with latest "Plots(v1.6.4)" and "RecipesBase" !

### ISSUE THREAD

**Issue by nuclear718** [dysonance/Indicators.jl#32] opened 2020-09-14 11:41 UTC
### Can not install "Indicators.jl" with latest "Plots(v1.6.4)" and "RecipesBase" !

**`Pkg.add("Indicators")`**

**My versioninfo():** 
Julia Version 1.5.1
Commit 697e782ab8 (2020-08-25 20:08 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: AMD Ryzen 5 3600X 6-Core Processor             
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, znver2)
Environment:
  JULIA.EXECUTABLEPATH = C:\Users\USER\AppData\Local\Julia-1.3.1\bin\ & set JULIA_NUM_THREADS=12 & julia.exe
  JULIA_NUM_THREADS = 12

**The return error message:**
>  Resolving package versions...
Unsatisfiable requirements detected for package RecipesBase [3cdcf5f2]:
 RecipesBase [3cdcf5f2] log:
 ├─possible versions are: [0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 1.0.0-1.0.2, 1.1.0] or uninstalled
 ├─restricted by compatibility requirements with Plots [91a5bcdd] to versions: [0.4.0, 0.5.0, 0.6.0, 0.7.0, 0.8.0, 1.0.0-1.0.2, 1.1.0]
 │ └─Plots [91a5bcdd] log:
 │   ├─possible versions are: [0.12.1-0.12.4, 0.13.0-0.13.1, 0.14.0-0.14.2, 0.15.0-0.15.1, 0.16.0, 0.17.0-0.17.4, 0.18.0, 0.19.0-0.19.3,

**Comment by JTAmos** [comment] 2020-09-15 14:08
This issue is ultimately also caused by the Temporal issue you raised. That release has been published now, and I have published a release for Indicators that will work with the newly published Temporal, so this issue should be resolved now. Links below to the Indicators releases. Closing now but again reopen if issue persists after updates.

https://github.com/dysonance/Indicators.jl/releases/tag/v0.8.1
https://github.com/JuliaRegistries/General/pull/21434

**Closed as completed by JTAmos** 2020-09-15 14:08 UTC
Labels: bug
