### ISSUE TITLE
TimeSeries not supported directly

### ISSUE THREAD

**Issue by imbrem** [dysonance/Indicators.jl#27] opened 2020-06-02 02:44 UTC
I wrote some wrappers for the indicators in this package taking in TimeArray arguments for my work, which uses the TimeSeries.jl package. I think it would be helpful for some people if these wrappers were available as part of the package: if desired, I can submit a PR.

**Comment by JTAmos** [comment] 2020-06-02 04:22
@imbrem Yes, please go ahead and submit a pull request. To the extent that the additional functionality is reasonably able to scale without too many dependency headaches, I'm happy to add more features.

**Comment by imbrem** [comment] 2020-06-02 14:47
I think all that's necessary is the TimeSeries package itself, though I'm a bit of a noob with Julia.

I do have one question though: I noticed that on the adapters for Temporal you by default take, for example, the SMA of :close, etc. You might have already implemented this, but does it make sense to include optional keyword args of what exactly to take the (e.g.) SMA of (and, for other more explicitly financial indicators, what columns correspond to open, high, low, close)?

**Comment by JTAmos** [comment] 2020-07-27 21:05
@imbrem To answer your question, the way that I would implement those keyword approaches would be to first extract out those desired column(s) first and then pass into the function, so that it doesn't have to the guesswork so to speak on finding the right column to compute on.

With respect to the TimeSeries support, I'm going to close this issue for now as this issues seems to be a duplicate of https://github.com/dysonance/Indicators.jl/issues/6. I'd be happy to consider a pull request if you find the time to work on getting this implemented, but for the time being I think this is a little outside the scope of the purpose of the package at this time.

**Closed as completed by JTAmos** 2020-07-27 21:05 UTC
